services: 
  mongo: 
    image: mongo:8.0.14 
    environment: 
      MONGO_INITDB_DATABASE: eventos_db 
    networks: 
      - db-network 
  redis:
    image: redis:8.2.2
    command: [
      "redis-server",
      "--maxmemory", "512mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    networks:
      - db-network
  backend: 
    build: 
      context: ./backend 
      dockerfile: Dockerfile 
    environment: 
      MONGO_URI: "mongodb://mongo:27017" 
      MONGO_DATABASE: "eventos_db" 
      REDIS_URI: "redis://redis:6379"
    ports: 
      - "8080:8080" 
    networks: 
      - db-network 
      - backend-network
    depends_on: 
      - mongo 
      - redis
  frontend: 
    build: 
      context: ./frontend 
      dockerfile: Dockerfile 
    ports: 
      - "8081:80" 
    networks:
      - backend-network
    depends_on: 
      - backend

networks:
  db-network:
    driver: bridge
  backend-network:
    driver: bridge  