services: 
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - backend-network
  mongo: 
    image: mongo:8.0.14 
    environment: 
      MONGO_INITDB_DATABASE: eventos_db 
    networks: 
      - db-network 
  redis:
    image: redis:8.2.2
    command: [
      "redis-server",
      "--maxmemory", "512mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    networks:
      - db-network
  backend: 
    build: 
      context: ./backend 
      dockerfile: Dockerfile 
    environment: 
      MONGO_URI: "mongodb://mongo:27017" 
      MONGO_DATABASE: "eventos_db" 
      REDIS_URI: "redis://redis:6379"
    expose: 
      - "8080"
    networks: 
      - db-network 
      - backend-network
    depends_on: 
      - mongo 
      - redis
  frontend: 
    build: 
      context: ./frontend 
      dockerfile: Dockerfile 
    expose:
      - "80"
    networks:
      - backend-network
    depends_on: 
      - backend

networks:
  db-network:
    driver: bridge
  backend-network:
    driver: bridge  